# Generated by Django 5.0.6 on 2026-06-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_source_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='source',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
