# Generated by Django 5.0.6 on 2026-06-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_connection_is_active_source_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='auth_method',
            field=models.CharField(choices=[('password', 'Password'), ('key', 'SSH Key')], default='password', max_length=10),
        ),
        migrations.AddField(
            model_name='connection',
            name='ssh_key',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='ssh_key_passphrase',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='ssh_pass',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
